### PR TITLE
➕ Add storybook

### PR DESCRIPTION
**Pull request by fre-ben**
- Add storybook
- Customize storybook setup
- Ignore `/storybook-static`
- Add `.eslintignore`

https://storybook.js.org/docs/react/get-started/install

### CODE REVIEW

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by fgottesmann — APPROVED** [review]
Clean, as always ;)

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
GJ 🚀

**Comment by SilviaBarcellini** [comment]
All good! 👍

**Review by cboenke — APPROVED** [review]
GJ, love the link collection in the README.md 🚀

**Review by mrana17 — APPROVED** [review]
Amazing! ✨

**Review by m-wiemers — APPROVED** [review]
I like your style 🕴

**Pull request merged**
