### PR TITLE
➕ Add custom server

### PR DESCRIPTION
**Pull request by fre-ben**
- Add custom Next.js server
- Add support for typescript and nodemon with custom server

https://nextjs.org/docs/advanced-features/custom-server
https://github.com/vercel/next.js/tree/canary/examples/custom-server-typescript

### CODE REVIEW

**Review by mrana17 — APPROVED** [review]
Freditastisch! 😼

**Review by christophvogel — APPROVED** [review]
GJ 💯

**Review by m-wiemers — APPROVED** [review]
You are an artist. Thank you!

**Review by JuKahl — APPROVED** [review]
GJ 🚀

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Comment by SilviaBarcellini** [comment]
All very good! 👍

**Review by fgottesmann — APPROVED** [review]
Very nice! :)

**Pull request merged**
