### PR TITLE
➕ Add Husky and lint-staged

### PR DESCRIPTION
**Pull request by fre-ben**
- Add Husky
- Add lint-staged
- Add `.lintstagedrc.json`
- Add scripts for `npm test`
- Add pre-push husky script running `npm test`

In order to push without running husky add `--no-verify` to your git commands

https://typicode.github.io/husky/
https://github.com/okonet/lint-staged

### CODE REVIEW

**Comment by DNaunin** [comment]
LGTM! 🚀

**Review by christophvogel — APPROVED** [review]
LGTM 👍

**Review by JuKahl — APPROVED** [review]
GJ 🚀

**Review by m-wiemers — APPROVED** [review]
very gj 🚀

**Review by M-Sieger — APPROVED** [review]
Awesome !

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Pull request merged**
