### PR TITLE
👷 Add Node.js CI

### PR DESCRIPTION
**Pull request by fre-ben**
This workflow builds and tests the project with different Node versions.

### CODE REVIEW

**Review by ShiningElektra — APPROVED** [review]
gj 👍

**Comment by JuKahl** [comment]
GJ 💪

**Review by JuKahl — APPROVED** [review]

**Comment by SilviaBarcellini** [comment]
All good! 👍

**Review by cboenke — APPROVED** [review]
LGTM 🚀

**Pull request merged**
