### PR TITLE
➕ Add prettier dependency

### PR DESCRIPTION
**Pull request by fre-ben**
- Installed prettier
- Added `.prettierignore` to ignore build artifacts
- Added prettier script in `.package.json`
- Prettified existing code

https://prettier.io/docs/en/install.html

### CODE REVIEW

**Review by SilviaBarcellini — APPROVED** [review]
lgtm 👍

**Review by ShiningElektra — APPROVED** [review]
LGTM 👍👍

**Review by saschahaselhuhn — APPROVED** [review]
good job

**Review by RonjaMeinecke — APPROVED** [review]
lgtm💪

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Pull request merged**
